### ISSUE TITLE
bedwarslobby没有plugin.yml

### ISSUE THREAD

**Issue by Astra-520** [FaintCloudy/AdvantageBedwars#1]
bedwarslobby没有plugin.yml

**Comment by Astra-520** [comment]
启动还会出现
 [AdvantageBedwars] Enabling AdvantageBedwars v1.0.1
[03:40:26 WARN]: java.io.IOException: 系统找不到指定的路径。
[03:40:26 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[03:40:26 WARN]:        at java.io.File.createNewFile(Unknown Source)
[03:40:26 WARN]:        at me.faintcloudy.bedwars.Bedwars.loadRewardConfig(Bedwars.java:134)
[03:40:26 WARN]:        at me.faintcloudy.bedwars.Bedwars.onEnable(Bedwars.java:164)
[03:40:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:40:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[03:40:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:40:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[03:40:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[03:40:26 WARN]:        at java.lang.Thread.run(Unknown Source)
[03:40:26 WARN]: java.io.FileNotFoundException: plugins\AdvantageBedwars\rewards.yml (系统找不到指定的路径。)
[03:40:26 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[03:40:26 WARN]:        at java.io.FileOutputStream.open(Unknown Source)
[03:40:26 WARN]:        at java.io.FileOutputStream.<init>(Unknown Source)
[03:40:26 WARN]:        at com.google.common.io.Files$FileByteSink.openStream(Files.java:201)
[03:40:26 WARN]:        at com.google.common.io.Files$FileByteSink.openStream(Files.java:189)
[03:40:26 WARN]:        at com.google.common.io.ByteSource.copyTo(ByteSource.java:255)
[03:40:26 WARN]:        at com.google.common.io.Files.copy(Files.java:384)
[03:40:26 WARN]:        at me.faintcloudy.bedwars.Bedwars.loadRewardConfig(Bedwars.java:140)
[03:40:26 WARN]:        at me.faintcloudy.bedwars.Bedwars.onEnable(Bedwars.java:164)
[03:40:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:40:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[03:40:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:40:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[03:40:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[03:40:26 WARN]:        at java.lang.Thread.run(Unknown Source)
[03:40:26 WARN]: java.io.IOException: 系统找不到指定的路径。
[03:40:26 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[03:40:26 WARN]:        at java.io.File.createNewFile(Unknown Source)
[03:40:26 WARN]:        at me.faintcloudy.bedwars.Bedwars.loadMapConfig(Bedwars.java:153)
[03:40:26 WARN]:        at me.faintcloudy.bedwars.Bedwars.onEnable(Bedwars.java:171)
[03:40:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[03:40:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[03:40:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:40:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[03:40:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[03:40:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[03:40:26 WARN]:        at java.lang.Thread.run(Unknown Source)
[03:40:26 WARN]: [AdvantageBedwars] Default system encoding may have misread config.yml from plugin jar
[03:40:26 WARN]: [AdvantageBedwars] Default system encoding may have misread config.yml from plugin jar

**Comment by Astra-520** [comment]
购买资源时 铁 金不够 不要关闭gui 保留 更像hyp

**Comment by Astra-520** [comment]
并且需要死亡无敌3秒 死时可在空中移动

**Comment by Astra-520** [comment]
rush模式已经到了生成点已经三级 但计分板仍然显示2级

**Comment by Astra-520** [comment]
超能力起床剑客要加10tick的延迟 不然防砍的时候就可以激活
